/**
 * Fetches Points of Interest around Athens from the Overpass API
 * and writes them to src/data/generated/pois.ts.
 *
 * Usage: npm run fetch-pois
 * Run manually when the itinerary changes significantly.
 */

import { writeFileSync } from 'fs';
import { join } from 'path';

const ATHENS_BBOX = '37.95,23.68,38.01,23.78'; // [minLat,minLng,maxLat,maxLng]

const OVERPASS_URL = 'https://overpass-api.de/api/interpreter';

const QUERY = `
[out:json][timeout:30];
(
  node["tourism"="attraction"]["name"](${ATHENS_BBOX});
  node["historic"="archaeological_site"]["name"](${ATHENS_BBOX});
  node["amenity"="museum"]["name"](${ATHENS_BBOX});
  node["historic"="monument"]["name"](${ATHENS_BBOX});
  node["tourism"="viewpoint"]["name"](${ATHENS_BBOX});
);
out body;
`.trim();

interface OverpassNode {
  id: number;
  lat: number;
  lon: number;
  tags: Record<string, string>;
}

interface OverpassResult {
  elements: OverpassNode[];
}

function inferCategory(tags: Record<string, string>): string {
  if (tags.historic === 'archaeological_site') return 'archaeology';
  if (tags.amenity === 'museum' || tags.tourism === 'museum') return 'museum';
  if (tags.tourism === 'viewpoint') return 'viewpoint';
  if (tags.historic === 'monument') return 'landmark';
  if (tags.tourism === 'attraction') return 'landmark';
  return 'landmark';
}

async function main() {
  console.log('Fetching POIs from Overpass API…');

  const res = await fetch(OVERPASS_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: `data=${encodeURIComponent(QUERY)}`,
  });

  if (!res.ok) {
    throw new Error(`Overpass API error: ${res.status} ${res.statusText}`);
  }

  const data = (await res.json()) as OverpassResult;
  console.log(`  → ${data.elements.length} nodes received`);

  const pois = data.elements
    .filter((el) => el.tags?.name)
    .map((el) => ({
      id:          String(el.id),
      name:        el.tags.name,
      category:    inferCategory(el.tags),
      lat:         el.lat,
      lng:         el.lon,
      description: el.tags['description'] ?? el.tags['wikipedia'] ?? undefined,
    }));

  const outPath = join(process.cwd(), 'src/data/generated/pois.ts');
  const content = `import type { POI } from '../../lib/types';

// Generated by scripts/fetch-pois.ts — run manually when itinerary changes
// Last generated: ${new Date().toISOString().slice(0, 10)}
export const pois: POI[] = ${JSON.stringify(pois, null, 2)};
`;

  writeFileSync(outPath, content, 'utf-8');
  console.log(`  ✓ Written ${pois.length} POIs to src/data/generated/pois.ts`);
}

main().catch((err) => {
  console.error('fetch-pois failed:', err);
  process.exit(1);
});
